name: Build PDF

on: workflow_dispatch # manual trigger

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://dvnh87/pandoc-with-make-tikzcd-and-code-fonts:1.0
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF artifact
          path: build/categorical-circuits-of-components.pdf
          retention-days: 1
